jsOpgave/JavaScriptAssignment/JavaScriptAssignment/Models/ContactModel.cs
namespace JavaScriptAssignment.Models
{
    using System.ComponentModel.DataAnnotations;

    public class ContactModel
    {
        public string Name { get; set; }

        [Required]
        [EmailAddress]
        public string Email { get; set; }

        [Required]
        public string Message { get; set; }

        [Phone]
        public string Phone { get; set; }
    }
}

jsOpgave/JavaScriptAssignment/JavaScriptAssignment/Models/ErrorViewModel.cs
namespace JavaScriptAssignment.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

jsOpgave/JavaScriptAssignment/JavaScriptAssignment/Controllers/AtoaController.cs
namespace JavaScriptAssignment.Controllers
{
    using JavaScriptAssignment.Models;
    using Microsoft.AspNetCore.Mvc;
    using System;

    public class AtoaController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(ContactModel model)
        {
            // Checks if the state of the model is valid and corresponds with the model created
            if (!this.ModelState.IsValid)
            {
                // In case it isn't we pass the model back to the same view
                return this.View(model);
            }

            try
            {
                // Uses the streamwriter to append messages to a text document. Preferably you'd use a database to store this.
                using (var file = 
                    new System.IO.StreamWriter(@"C:\Users\nics\Desktop\NVS\Opgaver\Opgave 8 - JavaScript\Contact\contact.txt", true))
                {
                    file.Write(DateTime.Now.ToString()
                        + Environment.NewLine
                        + "Name: " + model.Name 
                        + "\nEmail: " + model.Email 
                        + "\nPhone: " + model.Phone 
                        + "\nMessage: " + model.Message 
                        + Environment.NewLine
                        + Environment.NewLine);
                }

                // Returns the user to the root upon submitting the contact formula
                    return this.RedirectToAction("Index", "Home");
            }
            catch
            {
                // In case of an error, the site is reloaded
                return this.View(model);
            }
        }
    }
}

jsOpgave/JavaScriptAssignment/JavaScriptAssignment/Controllers/HomeController.cs
namespace JavaScriptAssignment.Controllers
{
    using System.Diagnostics;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.Extensions.Logging;
    using JavaScriptAssignment.Models;

    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

jsOpgave/JavaScriptAssignment/JavaScriptAssignment/Controllers/JavaScriptController.cs
namespace JavaScriptAssignment.Controllers
{
    using Microsoft.AspNetCore.Mvc;

    public class JavaScriptController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult JavaScriptGame()
        {
            return View();
        }
    }
}

jsOpgave/JavaScriptAssignment/JavaScriptAssignment/Controllers/MapBoxController.cs
namespace JavaScriptAssignment.Controllers
{
    using Microsoft.AspNetCore.Mvc;

    public class MapBoxController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

jsOpgave/JavaScriptAssignment/JavaScriptAssignment/Views/Atoa/Index.cshtml
@model JavaScriptAssignment.Models.ContactModel

@{
    ViewData["Title"] = "Contact us";
}

<h1>Contact us</h1>

<hr />
<div class="row">
    <div class="col-md-12">
        <form asp-action="Index">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-row">
                <div class="col-md-4">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="col-md-4">
                    <label asp-for="Email" class="control-label"></label>
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
                <div class="col-md-4">
                    <label asp-for="Phone" class="control-label"></label>
                    <input asp-for="Phone" class="form-control" />
                    <span asp-validation-for="Phone" class="text-danger"></span>
                </div>
            </div>
            <div class="form-row">
                <div class="col-md-12">
                    <label asp-for="Message" class="control-label"></label>
                    <textarea asp-for="Message" rows="3" class="form-control"></textarea>
                    <span asp-validation-for="Message" class="text-danger"></span>
                </div>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Submit" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<script src="~/js/counter.js"></script>

jsOpgave/JavaScriptAssignment/JavaScriptAssignment/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>This is a small assignment which shows off some JavaScript.</p>
</div>

jsOpgave/JavaScriptAssignment/JavaScriptAssignment/Views/JavaScript/Index.cshtml
@{
    ViewData["Title"] = "JavaScript øvelser";
}


<div class="container">

    <div class="row">
        <div class="col-sm col-12 d-flex justify-content-center">
            <h1>JavaScript Øvelser</h1>
        </div>
    </div>

    <br />

    <div class="row">
        <div class="col-sm col-12 d-flex justify-content-center">
            <h2>Øvelse 1 - Vis hvad dag det er!</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-sm col-12 d-flex justify-content-center">
            <p id="dag"></p>
        </div>
    </div>

    <br />

    <div class="row">
        <div class="col-sm col-12 d-flex justify-content-center">
            <h2>Øvelse 2 - Metode med navn!</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-sm col-12 d-flex justify-content-center">
            <p id="metodeNavn"></p>
        </div>
    </div>

    <br />

    <div class="row">
        <div class="col-sm col-12 d-flex justify-content-center">
            <h2>Øvelse 3 - Objekt med navn!</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-sm col-12 d-flex justify-content-center">
            <p id="objektNavn"></p>
        </div>
    </div>
</div>

jsOpgave/JavaScriptAssignment/JavaScriptAssignment/Views/JavaScript/JavaScriptGame.cshtml
@{
    ViewData["Title"] = "JavaScript game";
}


    <div class="container">
        <div class="row">
            <div class="col-12 d-flex justify-content-center">
                <h1>JavaScript game</h1>
            </div>
        </div>

        <br />

        <div class="row">
            <div id="obstacleGame" class="col-12 d-flex justify-content-center">
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-12 d-flex justify-content-center">
                <h3>Top score: <em id="score"></em></h3>
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-12 d-flex justify-content-center">
                <button id="reset" class="btn-info btn">Reset game</button>
            </div>
        </div>
    </div>

<script src="~/js/ObstacleGame.js"></script>

jsOpgave/JavaScriptAssignment/JavaScriptAssignment/Views/MapBox/Index.cshtml
@{
    ViewData["Title"] = "Mapbox Map";
}

<div id='map'></div>

<script src="~/js/mapbox.js"></script>

jsOpgave/JavaScriptAssignment/JavaScriptAssignment/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - JavaScript assignment</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/mapbox.css" />
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <script src='https://api.tiles.mapbox.com/mapbox-gl-js/v1.12.0/mapbox-gl.js'></script>
    <link href='https://api.tiles.mapbox.com/mapbox-gl-js/v1.12.0/mapbox-gl.css' rel='stylesheet' />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="JavaScript" asp-action="Index">JavaScript assignments</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="JavaScript" asp-action="JavaScriptGame">JavaScript game</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MapBox" asp-action="Index">Mapbox map</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Atoa" asp-action="Index">Contact A-to-A</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div id="sharedfooter" class="container">
            &copy; 2020 - JavaScript assignment
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/visdag.js"></script>
    <script src="~/js/metodenavn.js"></script>
    <script src="~/js/objektnavn.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>